apiVersion: apps/v1
kind: Deployment
metadata:
  name: kontain-test-app
spec:
  selector:
    matchLabels:
      kontain: test-app
  template:
    metadata:
      labels:
        kontain: test-app
    spec:
      runtimeClassName: kontain
      containers:
      - name: kontain-test-app
        image: localhost/krun-test:latest
        imagePullPolicy: IfNotPresent
