
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization


bases:
- ../../../demo-dweb

nameSuffix: -azure-demo

# TODO: pass registry/tag from Makefiles as 'kustomize edit'. For info
# see https://kubectl.docs.kubernetes.io/pages/app_management/container_images.html
images:
  - name: "dweb-km"
    newName: kontainkubecr.azurecr.io/dweb-km
    newTag: latest

